services:
  mysql:
    image: mysql:8.0
    container_name: attendance_mysql
    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: attendance_db
      MYSQL_USER: attendance_user
      MYSQL_PASSWORD: attendance_pass

    ports:
      - "3307:3306"

    volumes:
      - attendance_mysql_data:/var/lib/mysql

volumes:
  attendance_mysql_data: